export const products = [
    {
        id: 1,
        title: 'Chasing waterfalls in Sierras Grandes',
        price: 12000,
        stock: 10,
        category: 'nature',        
        img: '/sanclemente.webp',
        
    },
    {
        id: 2,
        title: 'EcoTour La Cumbrecita',
        price: 15000,
        stock: 10,
        category: 'nature',
        img: '/lacumbrecita.webp',
    },
    {
        id: 3,
        title: 'Trekking at Los Gigantes',
        price: 10000,
        stock: 10,
        category: 'nature',
        img: '/losgigantes.webp',
    },
    {
        id: 4,
        title: 'Bike tour',
        price: 7500,
        stock: 10,
        category: 'city',
        img: '/ciudad.webp',
    },
    {
        id: 5,
        title: 'Cathedrals experience',
        price: 8500,
        stock: 10,
        category: 'city',
        img: '/catedral.webp',
    },
    {
        id: 6,
        title: 'Museum Night',
        price: 9000,
        stock: 10,
        category: 'city',
        img: '/museo.webp',
    },
    {
        id: 7,
        title: 'Brunch Time at Santa Calma',
        price: 1500,
        stock: 10,
        category: 'gastronomy',
        img: '/santacalma.webp',
    },
    {
        id: 8,
        title: 'Sweet delight in La Capke',
        price: 2000,
        stock: 10,
        category: 'gastronomy',
        img: '/merienda.webp',
    },
    {
        id: 9,
        title: 'Dinner in El Meson',
        price: 1000,
        stock: 10,
        category: 'gastronomy',
        img: '/elmeson.webp',
    },
]